config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/eosc-node-endpoint-ui:
      branch: main
      repo: https://github.com/madgeek-arc/eosc-node-endpoint-ui.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-olive-owl.sh
        container: qc.acc_skanky-olivine-stoat
  QC.Doc:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-heliotrope-hyrax.sh
        container: qc.doc_leaky-thistle-hornet
      github.com/madgeek-arc/eosc-node-endpoint-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-carmine-goose.sh
        container: qc.doc_randy-orange-antelope
      github.com/madgeek-arc/eosc-node-endpoint-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-peach-barnacle.sh
        container: qc.doc_thirsty-cerulean-wolverine
  QC.Lic:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-heliotrope-horse.sh
        container: qc.lic_stinky-red-greyhound
  QC.Sty:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint-ui hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-goldenrod-tang.sh
        container: qc.sty_homely-tan-hippopotamus
      github.com/madgeek-arc/eosc-node-endpoint-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-purple-ferret.sh
        container: qc.sty_muzzy-maroon-kangaroo
  QC.Ver:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-burgundy-eagle.sh
        container: qc.ver_cheeky-silver-flamingo
timeout: 5400
