config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/pynblint
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/madgeek-arc/eosc-node-endpoint-ui:
      branch: main
      repo: https://github.com/madgeek-arc/eosc-node-endpoint-ui.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-ivory-whippet.sh
        container: qc.acc_tasty-ultramarine-bloodhound
  QC.Doc:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint-ui find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-jade-coral.sh
        container: qc.doc_shaky-russet-mastiff
      github.com/madgeek-arc/eosc-node-endpoint-ui git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-sepia-bulldog.sh
        container: qc.doc_slaphappy-wisteria-dragonfly
      github.com/madgeek-arc/eosc-node-endpoint-ui markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-rose-mist.sh
        container: qc.doc_chummy-gold-wallaby
  QC.Lic:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint-ui licensee:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-celadon-clam.sh
        container: qc.lic_pretty-coral-turkey
  QC.Sty:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint-ui hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-rust-meerkat.sh
        container: qc.sty_gloppy-indigo-horse
      github.com/madgeek-arc/eosc-node-endpoint-ui jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-red-woodlouse.sh
        container: qc.sty_wheezy-lavender-flounder
  QC.Ver:
    repos:
      github.com/madgeek-arc/eosc-node-endpoint-ui get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-cinnabar-cat.sh
        container: qc.ver_smelly-mauve-frise
timeout: 5400
